import '@repo/ui/styles/globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inder } from 'next/font/google';

import { env } from '@/config/env';

// import './globals.css';
import AppProvider from './provider';
import ReactScan from './react-scan';

const inter = Inder({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {env.NODE_ENV === 'development' && <ReactScan />}
      <body className={`${inter.variable} antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
